### ISSUE TITLE
admin-port visit not found

### ISSUE THREAD

**Issue by leland17** [flomesh-io/pipy#157]
## Bug Report

Make sure to review these points before submitting issues - thank you!

so bad, follow the instruction and do not find the visit the 6060 port;

![image](https://github.com/flomesh-io/pipy/assets/9267662/bd945955-5956-4c96-8880-17befd793cc1)

![1687049887425](https://github.com/flomesh-io/pipy/assets/9267662/f38004d2-ca47-40a7-9deb-a125cee2de85)

**Comment by khas-flomesh** [comment]
Hello Liao,

The  admin port does exist, you could found that's HTTP 404, not `connection refused`.
Please try:
```
http://localhost:6060/
```
Cheers,
Kevein

**Comment by leland17** [comment]
tab the command `build.sh -h`, it could find that pipy binary is builded without GUI by default.

**Comment by pajama-coder** [comment]
Hi @leland17 
When built without GUI, curling localhost:6060 will give you 404 because that's where the homepage is supposed to be accessed by a browser, however, other admin paths that are not browser/GUI related should work just fine. For instance, you can curl localhost:6060/repo and get a list of all codebases currently in the repo.

Make sure you build Pipy with GUI included (build.sh -g) to have localhost:6060 available to browsers.

This is not a bug.
